//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandyFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boxes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Boxes()
        {
            this.CustomerOrders = new HashSet<CustomerOrders>();
        }
    
        public int BoxId { get; set; }
        public Nullable<double> BoxWeight { get; set; }
        public string BoxName { get; set; }
        public Nullable<int> CandyId { get; set; }
    
        public virtual Candies Candies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOrders> CustomerOrders { get; set; }
    }
}
