//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandyFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentOrders
    {
        public int ComponentOrderId { get; set; }
        public int CustomerOrderId { get; set; }
        public int ComponentId { get; set; }
        public string ComponentName { get; set; }
        public Nullable<double> ComponentAmount { get; set; }
        public int CounterpartyId { get; set; }
        public string CounterpartyName { get; set; }
        public Nullable<float> OrderSum { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    
        public virtual Components Components { get; set; }
        public virtual Counterparties Counterparties { get; set; }
        public virtual CustomerOrders CustomerOrders { get; set; }
    }
}
