//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandyFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentOrder
    {
        public int OrderId { get; set; }
        public int ComponentId { get; set; }
        public Nullable<double> ComponentAmount { get; set; }
        public Nullable<decimal> OrderSum { get; set; }
        public Nullable<System.DateTime> OrderData { get; set; }
        public int BasedOrderId { get; set; }
        public string ComponentName { get; set; }
    
        public virtual Components Components { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
