//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandyFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrder
    {
        public int BoxId { get; set; }
        public Nullable<int> BoxesAmount { get; set; }
        public int OrderId { get; set; }
        public Nullable<decimal> OrderSum { get; set; }
        public Nullable<System.DateTime> OrderData { get; set; }
        public string BoxName { get; set; }
        public Nullable<double> BoxWeight { get; set; }
    
        public virtual Boxes Boxes { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
