//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandyFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerOrders()
        {
            this.ComponentOrders = new HashSet<ComponentOrders>();
        }
    
        public int CustomerOrderId { get; set; }
        public int BoxId { get; set; }
        public string BoxName { get; set; }
        public Nullable<double> BoxWeight { get; set; }
        public Nullable<int> BoxAmount { get; set; }
        public int CounterpartyId { get; set; }
        public string CounterpartyName { get; set; }
        public Nullable<float> OrderSum { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    
        public virtual Boxes Boxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComponentOrders> ComponentOrders { get; set; }
        public virtual Counterparties Counterparties { get; set; }
    }
}
